development:
  cloud_name: vianse
  api_key: '553295669295162'
  api_secret: 5ocuKqYpH1wHihgubTnlYMAmwxA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: vianse
  api_key: '553295669295162'
  api_secret: 5ocuKqYpH1wHihgubTnlYMAmwxA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: vianse
  api_key: '553295669295162'
  api_secret: 5ocuKqYpH1wHihgubTnlYMAmwxA
  enhance_image_tag: true
  static_image_support: false
